// Code generated by protoc-gen-go. DO NOT EDIT.
// source: door_comms.proto

/*
Package door_comms is a generated protocol buffer package.

It is generated from these files:
	door_comms.proto

It has these top-level messages:
	ProtoMsg
	DoorPing
	DoorPingResp
*/
package door_comms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	MsgType_DOOR_PING      MsgType = 0
	MsgType_DOOR_PING_RESP MsgType = 1
)

var MsgType_name = map[int32]string{
	0: "DOOR_PING",
	1: "DOOR_PING_RESP",
}
var MsgType_value = map[string]int32{
	"DOOR_PING":      0,
	"DOOR_PING_RESP": 1,
}

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}
func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (x *MsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgType_value, data, "MsgType")
	if err != nil {
		return err
	}
	*x = MsgType(value)
	return nil
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ProtoMsg struct {
	Type             *MsgType `protobuf:"varint,1,req,name=type,enum=door_comms.MsgType" json:"type,omitempty"`
	Msg              []byte   `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	Mac              *string  `protobuf:"bytes,3,req,name=mac" json:"mac,omitempty"`
	Sig              []byte   `protobuf:"bytes,4,req,name=sig" json:"sig,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoMsg) Reset()                    { *m = ProtoMsg{} }
func (m *ProtoMsg) String() string            { return proto.CompactTextString(m) }
func (*ProtoMsg) ProtoMessage()               {}
func (*ProtoMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoMsg) GetType() MsgType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MsgType_DOOR_PING
}

func (m *ProtoMsg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ProtoMsg) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *ProtoMsg) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type DoorPing struct {
	Timestamp        *int64 `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	PublicKey        []byte `protobuf:"bytes,2,req,name=publicKey" json:"publicKey,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DoorPing) Reset()                    { *m = DoorPing{} }
func (m *DoorPing) String() string            { return proto.CompactTextString(m) }
func (*DoorPing) ProtoMessage()               {}
func (*DoorPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DoorPing) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *DoorPing) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type DoorPingResp struct {
	Success          *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	DoorNum          *uint32 `protobuf:"varint,2,opt,name=doorNum" json:"doorNum,omitempty"`
	Error            *string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DoorPingResp) Reset()                    { *m = DoorPingResp{} }
func (m *DoorPingResp) String() string            { return proto.CompactTextString(m) }
func (*DoorPingResp) ProtoMessage()               {}
func (*DoorPingResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DoorPingResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *DoorPingResp) GetDoorNum() uint32 {
	if m != nil && m.DoorNum != nil {
		return *m.DoorNum
	}
	return 0
}

func (m *DoorPingResp) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*ProtoMsg)(nil), "door_comms.ProtoMsg")
	proto.RegisterType((*DoorPing)(nil), "door_comms.DoorPing")
	proto.RegisterType((*DoorPingResp)(nil), "door_comms.DoorPingResp")
	proto.RegisterEnum("door_comms.MsgType", MsgType_name, MsgType_value)
}

func init() { proto.RegisterFile("door_comms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x02, 0x6a, 0x72, 0x6a, 0xab, 0xe8, 0x60, 0xf0, 0xc0, 0x10, 0x65, 0x21, 0x42,
	0xa8, 0x03, 0x23, 0x73, 0x2b, 0xc4, 0xd0, 0x36, 0x3a, 0x18, 0xd8, 0xa2, 0x2a, 0x58, 0x51, 0x07,
	0x73, 0x96, 0xcf, 0x1d, 0xfa, 0xef, 0x91, 0x0d, 0x21, 0xdd, 0xee, 0x7b, 0xef, 0xde, 0xd3, 0x83,
	0xf2, 0x8b, 0xd9, 0x75, 0x3d, 0x1b, 0x23, 0x2b, 0xeb, 0xd8, 0x33, 0xc2, 0xa4, 0xd4, 0x1b, 0xc8,
	0xdb, 0x20, 0x6e, 0x65, 0xc0, 0x07, 0xb8, 0xf6, 0x67, 0xab, 0x55, 0x52, 0xa5, 0xcd, 0xf2, 0xf9,
	0x76, 0x75, 0x11, 0xdc, 0xca, 0xf0, 0x71, 0xb6, 0x9a, 0xe2, 0x03, 0x96, 0x90, 0x19, 0x19, 0x54,
	0x5a, 0xa5, 0xcd, 0x9c, 0xc2, 0x59, 0xbf, 0x40, 0xbe, 0x66, 0x76, 0xed, 0xf1, 0x7b, 0x88, 0xee,
	0xa1, 0x8f, 0x2d, 0x05, 0x85, 0x13, 0xef, 0xa1, 0xf0, 0x47, 0xa3, 0xc5, 0x1f, 0x8c, 0x8d, 0xa9,
	0x8c, 0x26, 0xa1, 0xfe, 0x84, 0xf9, 0x98, 0x25, 0x2d, 0x16, 0x15, 0xcc, 0xe4, 0xd4, 0xf7, 0x5a,
	0x24, 0x76, 0xe4, 0x34, 0x62, 0x70, 0xc2, 0xa6, 0xdd, 0xc9, 0xa8, 0xb4, 0x4a, 0x9a, 0x05, 0x8d,
	0x88, 0x77, 0x70, 0xa3, 0x9d, 0x63, 0xa7, 0xb2, 0x2a, 0x69, 0x0a, 0xfa, 0x85, 0xc7, 0x27, 0x98,
	0xfd, 0x0d, 0xc7, 0x05, 0x14, 0xeb, 0xfd, 0x9e, 0xba, 0xf6, 0x6d, 0xf7, 0x5a, 0x5e, 0x21, 0xc2,
	0xf2, 0x1f, 0x3b, 0xda, 0xbc, 0xb7, 0x65, 0xf2, 0x13, 0x00, 0x00, 0xff, 0xff, 0x41, 0x81, 0xc3,
	0xdf, 0x29, 0x01, 0x00, 0x00,
}
