// Code generated by protoc-gen-go. DO NOT EDIT.
// source: door_comms.proto

/*
Package door_comms is a generated protocol buffer package.

It is generated from these files:
	door_comms.proto

It has these top-level messages:
	ProtoMsg
	DoorPing
	DoorPingResp
	GetAction
	GetActionResp
	ActionComplete
	ActionCompleteResp
*/
package door_comms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	MsgType_DOOR_PING            MsgType = 0
	MsgType_DOOR_PING_RESP       MsgType = 1
	MsgType_GET_ACTION           MsgType = 2
	MsgType_GET_ACTION_RESP      MsgType = 3
	MsgType_ACTION_COMPLETE      MsgType = 4
	MsgType_ACTION_COMPLETE_RESP MsgType = 5
)

var MsgType_name = map[int32]string{
	0: "DOOR_PING",
	1: "DOOR_PING_RESP",
	2: "GET_ACTION",
	3: "GET_ACTION_RESP",
	4: "ACTION_COMPLETE",
	5: "ACTION_COMPLETE_RESP",
}
var MsgType_value = map[string]int32{
	"DOOR_PING":            0,
	"DOOR_PING_RESP":       1,
	"GET_ACTION":           2,
	"GET_ACTION_RESP":      3,
	"ACTION_COMPLETE":      4,
	"ACTION_COMPLETE_RESP": 5,
}

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}
func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (x *MsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgType_value, data, "MsgType")
	if err != nil {
		return err
	}
	*x = MsgType(value)
	return nil
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DoorAction int32

const (
	DoorAction_DOOR_UNLOCK DoorAction = 0
)

var DoorAction_name = map[int32]string{
	0: "DOOR_UNLOCK",
}
var DoorAction_value = map[string]int32{
	"DOOR_UNLOCK": 0,
}

func (x DoorAction) Enum() *DoorAction {
	p := new(DoorAction)
	*p = x
	return p
}
func (x DoorAction) String() string {
	return proto.EnumName(DoorAction_name, int32(x))
}
func (x *DoorAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DoorAction_value, data, "DoorAction")
	if err != nil {
		return err
	}
	*x = DoorAction(value)
	return nil
}
func (DoorAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ProtoMsg struct {
	Type             *MsgType `protobuf:"varint,1,req,name=type,enum=door_comms.MsgType" json:"type,omitempty"`
	Msg              []byte   `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	Mac              *string  `protobuf:"bytes,3,req,name=mac" json:"mac,omitempty"`
	Sig              []byte   `protobuf:"bytes,4,req,name=sig" json:"sig,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoMsg) Reset()                    { *m = ProtoMsg{} }
func (m *ProtoMsg) String() string            { return proto.CompactTextString(m) }
func (*ProtoMsg) ProtoMessage()               {}
func (*ProtoMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoMsg) GetType() MsgType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MsgType_DOOR_PING
}

func (m *ProtoMsg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ProtoMsg) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *ProtoMsg) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type DoorPing struct {
	Timestamp        *int64 `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	PublicKey        []byte `protobuf:"bytes,2,req,name=publicKey" json:"publicKey,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DoorPing) Reset()                    { *m = DoorPing{} }
func (m *DoorPing) String() string            { return proto.CompactTextString(m) }
func (*DoorPing) ProtoMessage()               {}
func (*DoorPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DoorPing) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *DoorPing) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type DoorPingResp struct {
	Success          *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	DoorNum          *uint32 `protobuf:"varint,2,opt,name=doorNum" json:"doorNum,omitempty"`
	Error            *string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	ActionRequired   *bool   `protobuf:"varint,4,opt,name=actionRequired" json:"actionRequired,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DoorPingResp) Reset()                    { *m = DoorPingResp{} }
func (m *DoorPingResp) String() string            { return proto.CompactTextString(m) }
func (*DoorPingResp) ProtoMessage()               {}
func (*DoorPingResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DoorPingResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *DoorPingResp) GetDoorNum() uint32 {
	if m != nil && m.DoorNum != nil {
		return *m.DoorNum
	}
	return 0
}

func (m *DoorPingResp) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *DoorPingResp) GetActionRequired() bool {
	if m != nil && m.ActionRequired != nil {
		return *m.ActionRequired
	}
	return false
}

type GetAction struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetAction) Reset()                    { *m = GetAction{} }
func (m *GetAction) String() string            { return proto.CompactTextString(m) }
func (*GetAction) ProtoMessage()               {}
func (*GetAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetActionResp struct {
	ActionId         *int64      `protobuf:"varint,1,opt,name=actionId" json:"actionId,omitempty"`
	ActionType       *DoorAction `protobuf:"varint,2,opt,name=actionType,enum=door_comms.DoorAction" json:"actionType,omitempty"`
	ActionPayload    []byte      `protobuf:"bytes,3,opt,name=actionPayload" json:"actionPayload,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GetActionResp) Reset()                    { *m = GetActionResp{} }
func (m *GetActionResp) String() string            { return proto.CompactTextString(m) }
func (*GetActionResp) ProtoMessage()               {}
func (*GetActionResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetActionResp) GetActionId() int64 {
	if m != nil && m.ActionId != nil {
		return *m.ActionId
	}
	return 0
}

func (m *GetActionResp) GetActionType() DoorAction {
	if m != nil && m.ActionType != nil {
		return *m.ActionType
	}
	return DoorAction_DOOR_UNLOCK
}

func (m *GetActionResp) GetActionPayload() []byte {
	if m != nil {
		return m.ActionPayload
	}
	return nil
}

type ActionComplete struct {
	ActionId         *int64 `protobuf:"varint,1,req,name=actionId" json:"actionId,omitempty"`
	Success          *bool  `protobuf:"varint,2,req,name=success" json:"success,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ActionComplete) Reset()                    { *m = ActionComplete{} }
func (m *ActionComplete) String() string            { return proto.CompactTextString(m) }
func (*ActionComplete) ProtoMessage()               {}
func (*ActionComplete) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ActionComplete) GetActionId() int64 {
	if m != nil && m.ActionId != nil {
		return *m.ActionId
	}
	return 0
}

func (m *ActionComplete) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

type ActionCompleteResp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ActionCompleteResp) Reset()                    { *m = ActionCompleteResp{} }
func (m *ActionCompleteResp) String() string            { return proto.CompactTextString(m) }
func (*ActionCompleteResp) ProtoMessage()               {}
func (*ActionCompleteResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*ProtoMsg)(nil), "door_comms.ProtoMsg")
	proto.RegisterType((*DoorPing)(nil), "door_comms.DoorPing")
	proto.RegisterType((*DoorPingResp)(nil), "door_comms.DoorPingResp")
	proto.RegisterType((*GetAction)(nil), "door_comms.GetAction")
	proto.RegisterType((*GetActionResp)(nil), "door_comms.GetActionResp")
	proto.RegisterType((*ActionComplete)(nil), "door_comms.ActionComplete")
	proto.RegisterType((*ActionCompleteResp)(nil), "door_comms.ActionCompleteResp")
	proto.RegisterEnum("door_comms.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("door_comms.DoorAction", DoorAction_name, DoorAction_value)
}

func init() { proto.RegisterFile("door_comms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xcf, 0x6f, 0xda, 0x30,
	0x14, 0xc7, 0xeb, 0x84, 0xaa, 0xc9, 0x2b, 0xa4, 0xd1, 0x2b, 0x9a, 0xac, 0x69, 0x93, 0xa2, 0x68,
	0xda, 0xa2, 0x1e, 0x7a, 0xe8, 0x61, 0xf7, 0x8a, 0x52, 0x84, 0x5a, 0x48, 0xe4, 0xb1, 0x33, 0xca,
	0x82, 0x15, 0x59, 0x22, 0x75, 0x16, 0x87, 0x03, 0x37, 0xae, 0xfb, 0xaf, 0x27, 0xdb, 0x40, 0x80,
	0xdb, 0xfb, 0x7e, 0xfc, 0x7e, 0x7e, 0x65, 0x08, 0x57, 0x52, 0x36, 0xcb, 0x42, 0x56, 0x95, 0x7a,
	0xac, 0x1b, 0xd9, 0x4a, 0x84, 0x8e, 0xc4, 0x02, 0xbc, 0x4c, 0xc3, 0x99, 0x2a, 0xf1, 0x07, 0xf4,
	0xda, 0x6d, 0xcd, 0x29, 0x89, 0x9c, 0x24, 0x78, 0xba, 0x7f, 0x3c, 0x29, 0x9c, 0xa9, 0x72, 0xb1,
	0xad, 0x39, 0x33, 0x09, 0x18, 0x82, 0x5b, 0xa9, 0x92, 0x3a, 0x91, 0x93, 0xf4, 0x99, 0x0e, 0x0d,
	0xc9, 0x0b, 0xea, 0x46, 0x4e, 0xe2, 0x33, 0x1d, 0x6a, 0xa2, 0x44, 0x49, 0x7b, 0x36, 0x47, 0x89,
	0x32, 0x7e, 0x05, 0xef, 0x45, 0xca, 0x26, 0x13, 0x1f, 0x25, 0x7e, 0x01, 0xbf, 0x15, 0x15, 0x57,
	0x6d, 0x5e, 0xd5, 0x66, 0x9e, 0xcb, 0x3a, 0xa0, 0x5f, 0xeb, 0xcd, 0x9f, 0xb5, 0x28, 0xde, 0xf8,
	0x76, 0x3f, 0xa5, 0x03, 0xf1, 0x8e, 0x40, 0xff, 0xd0, 0x88, 0x71, 0x55, 0x23, 0x85, 0x1b, 0xb5,
	0x29, 0x0a, 0xae, 0x94, 0x69, 0xe5, 0xb1, 0x83, 0xd4, 0x2f, 0xfa, 0x88, 0xf9, 0xa6, 0xa2, 0x4e,
	0x44, 0x92, 0x01, 0x3b, 0x48, 0x1c, 0xc2, 0x35, 0x6f, 0x1a, 0xd9, 0x50, 0x37, 0x22, 0x89, 0xcf,
	0xac, 0xc0, 0xef, 0x10, 0xe4, 0x45, 0x2b, 0xe4, 0x07, 0xe3, 0x7f, 0x37, 0xa2, 0xe1, 0x2b, 0xda,
	0x8b, 0x48, 0xe2, 0xb1, 0x0b, 0x1a, 0xdf, 0x82, 0x3f, 0xe1, 0xed, 0xb3, 0x81, 0xf1, 0x3f, 0x02,
	0x83, 0xa3, 0x32, 0x0b, 0x7d, 0x06, 0xcf, 0x16, 0x4c, 0x57, 0x94, 0x44, 0x24, 0x71, 0xd9, 0x51,
	0xe3, 0x4f, 0x00, 0x1b, 0x6b, 0x3f, 0xcd, 0x56, 0xc1, 0xd3, 0xa7, 0x53, 0xab, 0xf5, 0x69, 0xfb,
	0x5e, 0x27, 0x99, 0xf8, 0x0d, 0x06, 0x56, 0x65, 0xf9, 0x76, 0x2d, 0xf3, 0x95, 0x59, 0xbc, 0xcf,
	0xce, 0x61, 0xfc, 0x0a, 0x81, 0xad, 0x1d, 0xc9, 0xaa, 0x5e, 0xf3, 0x96, 0x5f, 0xec, 0xe2, 0x9c,
	0xed, 0x72, 0x62, 0x9c, 0x73, 0x66, 0x5c, 0x3c, 0x04, 0x3c, 0xef, 0xa3, 0xef, 0x7a, 0xd8, 0x11,
	0xb8, 0xd9, 0xff, 0x04, 0x1c, 0x80, 0xff, 0x92, 0xa6, 0x6c, 0x99, 0x4d, 0xe7, 0x93, 0xf0, 0x0a,
	0x11, 0x82, 0xa3, 0x5c, 0xb2, 0xf1, 0xaf, 0x2c, 0x24, 0x18, 0x00, 0x4c, 0xc6, 0x8b, 0xe5, 0xf3,
	0x68, 0x31, 0x4d, 0xe7, 0xa1, 0x83, 0xf7, 0x70, 0xd7, 0x69, 0x9b, 0xe4, 0x6a, 0xb8, 0x07, 0xa3,
	0x74, 0x96, 0xbd, 0x8f, 0x17, 0xe3, 0xb0, 0x87, 0x14, 0x86, 0x17, 0xd0, 0xa6, 0x5f, 0x3f, 0x7c,
	0x05, 0xe8, 0x0c, 0xc2, 0x3b, 0xb8, 0x35, 0x53, 0x7f, 0xcf, 0xdf, 0xd3, 0xd1, 0x5b, 0x78, 0xf5,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0x62, 0xba, 0x26, 0xac, 0xed, 0x02, 0x00, 0x00,
}
